serilog:
  minimumLevel:
    default: Information
    override:
      Microsoft: Error
      System.Net.Http.HttpClient: Error
      Microsoft.AspNetCore.Hosting.Diagnostics: Information
      Microsoft.Hosting.Lifetime: Information
      Elastic.Apm: Error
  writeTo:
    - name: Async
      args:
        configure:
          - name: Console
            args:
              theme: "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Literate, Serilog.Sinks.Console"
              outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} <s:{SourceContext}>{NewLine}{Exception}"
